# Generated by Django 3.0.5 on 2020-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='father_rank',
            field=models.CharField(choices=[('farmer', 'farmer'), ('labour', 'labour'), ('service', 'sevice'), ('dead', 'dead'), ('business', 'business'), ('company', 'company'), ('unemployed', 'unemployed')], default='farmer', max_length=50),
        ),
    ]
