# Generated by Django 3.0.5 on 2020-11-21 17:16

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20200910_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='img',
            field=models.ImageField(upload_to='pics/scholarship_pics', validators=[homepage.models.file_size]),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_form',
            field=models.FileField(upload_to='documents/scholarship_form/', validators=[homepage.models.file_size2]),
        ),
    ]
