# Generated by Django 3.0.5 on 2020-11-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20201121_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_table',
            name='status',
            field=models.CharField(blank=True, default='under observation', max_length=50, null=True),
        ),
    ]
