# Generated by Django 3.0.5 on 2020-11-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_auto_20201121_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_table',
            name='status',
        ),
        migrations.AddField(
            model_name='application_table',
            name='STATUS',
            field=models.CharField(choices=[('UNDER OBSERVATION', 'UNDER OBSERVTION'), ('PENDING', 'PENDING'), ('SELECTED', 'SELECTED'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=50),
        ),
    ]
