# Generated by Django 3.0.5 on 2020-11-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_auto_20201121_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_table',
            name='STATUS',
        ),
        migrations.AddField(
            model_name='application_table',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('UNDER OBSERVATION', 'UNDER OBSERVTION'), ('SELECTED', 'SELECTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50),
        ),
    ]
